ARG STACK_VERSION

FROM docker.elastic.co/logstash/logstash:${STACK_VERSION}

# Download JDBC connector for Logstash
# RUN curl -L --output "mysql-connector-java-8.0.22.tar.gz" "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.22.tar.gz" \
#     && tar -xf "mysql-connector-java-8.0.22.tar.gz" "mysql-connector-java-8.0.22/mysql-connector-java-8.0.22.jar" \
#     && mv "mysql-connector-java-8.0.22/mysql-connector-java-8.0.22.jar" "mysql-connector-java-8.0.22.jar" \
#     && rm -r "mysql-connector-java-8.0.22" "mysql-connector-java-8.0.22.tar.gz"

# Download postgres JDBC connector for Logstash
RUN curl -L --output "postgresql-42.6.0.jar" "https://jdbc.postgresql.org/download/postgresql-42.6.0.jar"

ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
