INSERT INTO game (name, img_url, platform, release_date, country, scores, developers, publishers, introduction, description)
VALUES
    ('Star Wars: The Deckbuilding Game',
     'https://assets-prd.ignimgs.com/2023/02/28/star-wars-the-deckbuilding-game-button-1677620694999.jpg',
     'xbox',
     '2023-3-3',
     'USA',
     8,
     'Designer Caleb Grace',
     'Fantasy Flight Games',
     'This head-to-head game for two players brings the galaxy-spanning war between the Galactic Empire and the Rebel Alliance to your tabletop.',
     'Star Wars: The Deckbuilding Game is a unique draft-style deck builder that features over 100 iconic characters and locations and allows you to craft your deck as you play.'
    ),
    ('Sons of the Forest',
     'https://assets-prd.ignimgs.com/2022/05/17/sonsoftheforest-1652806471329.jpg',
     'pc',
     '2023-2-23',
     'USA',
     8,
     'Endnight Games',
     'Endnight Games',
     'Sons of The Forest is the sequel to the terrifying first-person, open-world survival horror game where you must build, explore, and survive after a nearly-fatal helicopter crash in a mysterious forest.',
     'Even in early access, Sons of the Forest is already a strong survival crafter sequel that takes all the things The Forest did so well and does them a little bit better.'
    ),
    ('Wo Long: Fallen Dynasty',
     'https://assets-prd.ignimgs.com/2022/06/12/wo-long-button-1-1655066531634.jpg',
     'xbox',
     '2023-3-3',
     'USA',
     8,
     'Team Ninja',
     'Koei Tecmo',
     'Wo Long: Fallen Dynasty follows the dramatic, action-packed story of a nameless militia soldier fighting for survival in a dark fantasy version of the Later Han Dynasty where demons plague the Three Kingdoms.',
     'Familiar issues with storytelling and loot aside, Wo Long: Fallen Dynasty is another great entry in Team Ninjas growing collection of action RPGs that features some of the best combat in the soulslike genre, even though those battles start to lose their tension due to a distinct lack of enemy variety to fill out the 20+ hour runtime.'
    ),
    ('Gran Turismo 7',
    'https://assets-prd.ignimgs.com/2020/09/12/gran-turismo-7-button-sep2020-1599871750105.jpg',
    'playstation',
    '2022-3-4',
    'USA',
    9,
    'Polyphony Digital',
    'Sony Interactive Entertainment',
    'Gran Turismo 7 builds on 22 years of experience to bring you the best features from the history of the franchise.',
    'Mixing the original GTs trendsetting format with GT Spors stern but very successful focus on competitive online racing, Gran Turismo 7 makes a few errors but is a potent podium performance from developer Polyphony Digital.'
    ),
    ('Demeo',
    'https://assets-prd.ignimgs.com/2023/03/01/demeo-1677695808560.jpg',
    'playstation',
    '2021-5-6',
    'USA',
    8,
    'Resolution Games',
    'Resolution Games',
    'In the dungeon crawler RPG Demeo, dark force has taken over the underworld, and its world your not likely to survive alone.',
    'Demeo is a delightfully-distilled tabletop RPG experience for up to four players that fits just as well in VR as it does on PC or playstation.'
    ),
    ('Scars Above',
    'https://assets-prd.ignimgs.com/2022/08/25/scars-above-button-1661386581949.jpg',
    'pc',
    '2023-2-28',
    'USA',
    5,
    'Mad Head Games',
    'Prime Matter',
    'Scars Above is a challenging sci-fi third-person action adventure shooter combining the rewarding feel of overcoming difficulty with a compelling and intricate story, set in a mysterious alien world to explore.',
    'Scars Above is a journey into a mysterious planet that lacks polish, depth, and balance, preventing it from being a memorable third-person shooter.'
    ),
    ('Heroes 3-- Multiplayer', 
    'https://assets-prd.ignimgs.com/2023/02/28/coh3mp-1677544165499.jpg', 
    'pc', 
    '2023-02-23', 
    'Poland', 
    8, 
    'Relic', 
    'SEGA', 
    'Company of Heroes 3 brings the series'' intimate boots-on-the-ground storytelling to a brand-new theatre of war, unlocking authentic new tactics, factions, and a wealth of untold stories from World War II.', 
    'For a lot of long-time fans, Company of Heroes is a real-time strategy series that''s more about competitive play than single-player campaigns, and we''ve logged hundreds more hours playing against other people than against the AI in scripted scenarios. That''ll certainly be true for Company of Heroes 3, because while the single-player campaigns are trapped in a quagmire of a strategic map and bogged down in their storytelling, in multiplayer we can focus on what really matters: moment-to-moment gameplay, balance, and faction mechanics. CoH3 nails all of that thanks to a wide variety of factions, snappy unit controls, and great multiplayer stability.'),
    ('Resident Evil Village',
    'https://assets-prd.ignimgs.com/2023/02/24/revillagevr-blogroll-1677278140297.jpg', 
    'pc', 
    '2021-05-07', 
    'Japan', 
    8, 
    'Capcom', 
    'Capcom', 
    'Fear surrounds you in Resident Evil Village, the eighth main entry in the storied Resident Evil horror franchise.', 
    'Everybody knows Lady Dimitrescu is tall, but I was still shocked to see just how large she loomed over me from a first-person angle in VR. Resident Evil Village VR captured my undivided attention even beyond my fascination for the tall vampire lady, offering a fresh perspective on a nearly two-year-old game I have played a dozen times over. From the robust tutorial before you start playing to the many ways you can customize the controls for the most comfortable experience, Resident Evil Village''s VR mode is no afterthought, but rather a well-crafted and exciting way to experience an already excellent game.'),
    ('Parks Board', 
    'https://assets-prd.ignimgs.com/2023/02/27/parks-blogroll-1677522832358.png?', 
    'xbox', 
    '2023-02-23', 
    'USA', 
    8,
    'Keymaster Games', 
    'Nintendo', 
    'PARKS is a celebration of the US National Parks featuring illustrious art from Fifty-Nine Parks.', 
    'America is justly proud of its remaining areas of untamed wilderness, much of which is preserved through its national parks system. It''s been an inspiration to both artists and board game designers down the years, the latter giving us titles as diverse as hobby fare Cascadia to the much more mainstream National Parks-Opoly. But 2019''s PARKS aims to give you the best of both worlds with some accessible tactical play married to art from the 59 Parks print series.'),
    ('Blood Bowl 3', 
    'https://assets-prd.ignimgs.com/2023/02/25/bloodbowl3-blogroll-1677284729619.jpg', 
    'playstation', 
    '2023-02-23',
    'France', 
    5, 
    'Cyanide', 
    'Nacon', 
    'Blood Bowl III is fantasy football in action -- a turn-based strategy game inspired where elves, humans, orcs and other creatures fight for the ball with shoulder charges, kicks, punches and weapons', 
    'Many traditional sports games release a new edition every year, with mixed results on whether or not they feel different enough to justify themselves beyond a roster update. So I''m surprised at Blood Bowl 3, the latest digital adaptation of Games Workshop''s ultraviolent board game parody of American football set in a wacky alternate version of the Warhammer Fantasy universe. It presents shockingly little reason for its own existence compared to the previous version, which came out almost eight years ago. I like the intense and hilarious premise and mechanics of Blood Bowl on their own, but what we have here is basically Blood Bowl 2, again, but worse.'),
    ('Kirby''s Return to Dream Land Deluxe', 
    'https://assets-prd.ignimgs.com/2023/02/22/kirby-blogroll-1677029467434.jpg', 
    'xbox', 
    '2023-02-24', 
    'Japan', 
    7, 
    'HAL Laboratory', 
    'Nintendo', 
    'This remake of the 2011 2.5D sidescroller features four-player co-op gameplay on top of the original campaign and minigame collections.', 
    'Kirby''s Return to Dream Land has been solidly in the former camp since its original release on Wii in 2011, making its Deluxe rerelease on Switch recognizable in more ways than one. Strong platforming fundamentals, creative late-game level design, and some worthwhile new content still make it worth revisiting, but it''s a more appealing package for newcomers than those who have already gone on the original adventure.'),
    ('Heroes 3-Single Player Campaigns', 
    'https://assets-prd.ignimgs.com/2023/02/20/coh3-background-overlay-0-1676910729324.jpg', 
    'pc', 
    '2023-02-21',
    'Poland', 
    6, 
    'Relic', 
    'SEGA', 
    'Company of Heroes 3 brings the series'' intimate boots-on-the-ground storytelling to a brand-new theatre of war, unlocking authentic new tactics, factions, and a wealth of untold stories from World War II.', 
    'Writing this review hurt my feelings. The Company of Heroes series is near and dear to my heart – all three of them are real-time strategy games that cut to the core of the genre, focusing on overarching strategic decisions coupled with tactical troop movements and a battlefield that truly matters. I''m pleased to say that Company of Heroes 3 implements those series fundamentals quite well in a gentle remix that brings the series to diverse theaters of World War 2 that it hadn''t touched yet. What I''m very displeased about is that the ambitious Italian campaign mode is incredibly disappointing. While individual missions and scenarios within the strategic sandbox are strong and even thrilling at times, almost every feature on the strategic map doesn''t work, either because it''s bugged or because it''s such middle-of-the-road game design that it''s simply boring.'),
    ('Atomic Heart',
    'https://assets-prd.ignimgs.com/2023/02/20/atomic-heart-blog-1676878709313.jpg',
    'xbox',
    '2023-02-21', 
    'Russia',
    8,
    'Mundfish',
    'Focus Entertainment',
    'Atomic Heart is an adventure first-person shooter, events of which unfold in an alternative universe, during the high noon of the Soviet Union.',
    'Atomic Heart is a highly imaginative, atompunk-inspired attempt at picking up where the likes of BioShock left off that makes missteps but definitely has the ticker to punch well above its weight.'),

    ('Metroid Prime: Remastered',
    'https://assets-prd.ignimgs.com/2023/02/17/metroidprimeremastered-blogroll-2-1676667173405.jpg',
    'xbox',
    '2023-02-8', 
    'Japan',
    10,
    'Retro Studios',
    'Nintendo',
    'Metroid Prime: Remastered is a twin-stick, visually upgraded port of the Retro Studios-developed first-person action adventure, originally released for GameCube in 2002.',
    'Metroid Prime Remastered honors a lauded classic and brings it up to code, fixing outdated controls and adding a slick coat of polygons and textures that make this masterpiece of a shooter shine once more.'
	),
	('Octopath Traveler II',
    'https://assets-prd.ignimgs.com/2023/02/17/octopathtravelerii-blogroll-1676607021587.jpg',
    'pc',
    '2023-02-24', 
    'Japan',
    7,
    'Square Enix, Acquire',
    'Square Enix',
    'Venture into the world of Solistia and experience a new era with eight brand-new travelers in Octopath Traveler II, an RPG sequel which takes the series'' HD-2D graphics, a fusion of retro pixel art and 3DCG, to even greater heights..',
    'Octopath Traveler 2 is a very enjoyable JRPG sequel that feels a little too safe and familiar.'),
    ( 'Like a Dragon: Ishin',
    'https://assets-prd.ignimgs.com/2023/02/14/likeadragonishin-blogroll-1676417638549.jpg',
    'pc',
    '2023-02-21', 
    'Japan',
    7,
    'Ryu Ga Gotoku Studio',
    'SEGA',
    'Like a Dragon: Ishin is an action-packed samurai historical thriller set in 1860s Kyo, a fictionalized version of Kyoto. In Ishin, you can slash through foes with a lethal blade using the Swordsman style or sharpshoot your enemies with a revolver using the Gunman style..',
    'Like a Dragon: Ishin! is an enjoyable and interesting spin-off from the Yakuza series, but not an essential one.'
	),
    ('Star Wars: Tales from the Galaxy''s Edge',
    'https://assets-prd.ignimgs.com/2023/02/17/starwarstalesfromgalaxysedge-enhanced-blogroll-1676595006983.jpg',
    'xbox',
    '2020-11-19', 
    'USA',
    7,
    'Lucasfilm, ILMxLAB, Oculus VR',
    'Disney Electronic Content',
    'Get ready for an adventure on the planet of Batuu -- in stunning virtual reality with Star Wars: Tales from the Galaxy''s Edge, an action-adventure virtual reality experience connected to the world of Star Wars: Galaxy''s Edge.',
    'Star Wars: Tales from the Galaxy''s Edge Enhanced Edition is an excellent way to showcase the best features of a fancy new playstation VR2. The first few hours of the story are its Episodes I and II (bad) but then things turn around and immerse us in Star Wars greatness.'
	),
    ('Wild Hearts',
    'https://assets-prd.ignimgs.com/2023/02/11/wildhearts-blogroll-1676148031379.jpg',
    'pc',
    '2023-2-16', 
    'USA',
    8,
    'Koei Tecmo',
    'Electronic Arts, Koei Tecmo',
    'Wild Hearts'' building mechanics add a very fun twist to its familiar but well-executed co-op monster hunting formula..',
    'Wild Hearts is a monster hunting game set in Azuma – effectively a fantasy feudal Japan – in which teams of up to three players take on giant nature-infused beasts called Kemono.'
	),
    ('Pokemon Scarlet', 
    'https://assets-prd.ignimgs.com/2022/08/03/pokemon-scarlet-1659542292648.jpg',
    'nintendo',
    '2022-11-18',
    'Japan',
    6, 
    'Game Freak', 
    'Game Freak', 
    'Catch never-before-seen Pokemon and explore a brand new region created playable with new open-world gameplay in Pokemon Scarlet and Pokemon Violet! Brand new Pokemon populate this world -- who will be your new starter partner: Sprigatito, Fuecoco, or Quaxly?', 
    'The open-world gameplay of Pokémon Scarlet and Violet is a brilliant direction for the future of the franchise, but this promising shift is sabotaged by the numerous ways in which Scarlet and Violet feel deeply unfinished.'),
    ('The King of Fighters XV', 
    'https://assets-prd.ignimgs.com/2021/10/28/king-of-fighters-xv-button-fin-1635398098319.jpg', 
    'playstation', 
    '2022-02-17', 
    'Japan',
    8, 
    'SNK Corporation', 
    'SNK Corporation', 
    'The King of Fighters XV continues SNK''s long-running fighting game franchise.',
    'The King of Fighters XV still feels left in the past when it comes to its single player offerings, but what it lacks in ambition, it makes up in solid fundamentals and great netcode that make the online experience the best the series has ever seen. Mitchell Saltzman Avatar'),
    ('Monster Hunter Rise', 
    'https://assets-prd.ignimgs.com/2020/09/17/monster-hunter-rise-button-1600361562743.jpg',
    'playstation', 
    '2021-05-25', 
    'Japan', 
    8, 
    'Capcom', 
    'Capcom',
    'Rise to the challenge and join the hunt! In Monster Hunter Rise, battle fearsome monsters and use your rewards to craft a huge variety of epic weapons and armor.', 
    'Monster Hunter Rise mixes classic Monster Hunter ideas with some of World''s best improvements and a whole bunch of clever new mechanics of its own.'),
    ('Monster Hunter World: Iceborne', 
    'https://assets1.ignimgs.com/2019/07/17/monster-hunter-world-iceborne---button-fin-1563323108549.jpg', 
    'playstation', 
    '2019-09-06', 
    'Japan',
    9, 
    'Capcom',
    'Capcom', 
    'The first major DLC package for the hit monster hunting game, Monster Hunter World: Iceborne is a new story that begins after the events of the main game.', 
    'Monster Hunter World: Iceborne adds loads of impressive monsters and tons of quality-of-life improvements to an already incredible game.'),
    ('Devil May Cry 5', 
    'https://assets1.ignimgs.com/2019/03/04/devil-may-cry-5---button-fin-1551739966394.jpg', 
    'playstation', 
    '2019-03-08', 
    'Japan', 
    9.5, 
    'Capcom',
    'Capcom', 
    'More flash and flair than ever before! DMC returns to bring gamers the legendary fast-paced action you love, the devilish combat you crave!',
    'Devil May Cry 5''s trio of outstanding combat styles set a new high bar for the series, and its mysterious story keeps things interesting along the way.'),
    ('Street Fighter V', 
    'https://assets-prd.ignimgs.com/2022/01/07/street-fighter-v-button-crop-1641543692786.jpg', 
    'playstation', 
    '2016-02-15', 
    'Japan',
    8, 
    'Capcom', 
    'Capcom', 
    'Street Fighter 5 is a first-rate competitive fighting game, but disappointingly thin in single-player content.', 
    'Quarter up for the fifth game of this dominating fighter franchise.'),
    ('Total War: Warhammer3',
    'https://assets-prd.ignimgs.com/2021/02/03/total-war-warhammer-3-button-02-1612376264737.jpg' , 
    'pc', 
    '2022-02-17', 
    'UK', 
    9, 
    'Creative Assembly', 
    'SEGA', 
    'Total War: Warhammer III plunges players into a cataclysmic conflict between ruinous daemonic powers and the sentinels of the mortal world. Each choice you make will shape the reality-shattering conflict to come.', 
    'The cataclysmic conclusion to the Total War: WARHAMMER trilogy is here. Rally your forces and step into the Realm of Chaos, a dimension of mind-bending horror where the very fate of the world will be decided. Will you conquer your Daemons… or command them?' 
	),
    ('Company of Hero3', 
    'https://assets-prd.ignimgs.com/2022/07/12/company-of-heroes-3-button-resize-1657653328088.jpg', 
    'pc', 
    '2023-02-24', 
    'Canada',
    6, 
    'Relic Entertainment', 
    'SEGA', 
    'Company of Heroes 3''s single-player campaigns remix the series'' signature WW2 combat, but they wrap it up in a boring, buggy strategic map and a mismatched story.', 
    'Bigger and better than ever, Company of Heroes 3 combines heart-pounding combat with deeper strategic choices in a stunning Mediterranean theatre of war. In Company of Heroes 3, every battle tells a story...what''s yours?'),
    ('Heart of Iron4',
    'https://assets2.ignimgs.com/2014/02/21/hearts-of-iron-iv-button-02jpg-e3064e.jpg', 
    'pc', 
    '2015-06-06',
    'Sweden', 
    9, 
    'Paradox Development Studio', 
    'Paradox Interactive', 
    'Hearts of Iron 4''s detailed World War 2 sim makes it a contender for the title of ultimate armchair general game.',
    'Victory is at your fingertips! Your ability to lead your nation is your supreme weapon, the strategy game Hearts of Iron IV lets you take command of any nation in World War II; the most engaging conflict in world history.' ),
    ('Warframe', 
    'https://assets1.ignimgs.com/2019/02/22/warframe---button-1550875935085.jpg', 
    'nintendo', 
    '2013-03-25', 
    'Canada', 
    8.6,
    'Digital Extremes', 
    'Digital Extremes', 
    'Warframe isn''t an easily approachable game, but it''s one that''s worth getting comfortable with.', 
    'Awaken as an unstoppable warrior and battle alongside your friends in this story-driven free-to-play online action game'),
    ('Elder Scroll Online',
    'https://assets-prd.ignimgs.com/2022/01/05/elderscrollsonline-1641413357689.jpg', 
    'xbox', 
    '2015-06-09', 
    'USA',
    8, 
    'Zenimax Online Studio', 
    'Bethesda Studio', 
    'The Elder Scrolls Online: TU''s combat handles well on a gamepad, making it a great way to experience all this content.', 
    'Join over 20 million players in the award-winning online multiplayer RPG and experience limitless adventure in a persistent Elder Scrolls world. Battle, craft, steal, or explore, and combine different types of equipment and abilities to create your own style of play. No game subscription required.'),
    ('World of Warcraft: DragonFlight',
    'https://assets-prd.ignimgs.com/2022/04/19/wow-dragonflight-button-1-1650398895381.jpg', 
    'pc',
    '2022-11-28', 
    'USA',
    7, 
    'Blizzard Entertainment', 
    'Blizzard Entertainment',
    'Dragonflight is a sharply-written and breathtaking experience for the first few dozen hours, but suffers from somewhat threadbare endgame options.', 
    'Journey through a lost realm of magic and wonder as you explore forgotten shores. Soar on your own dragon with the all new flight mechanic, Dragonriding.'),
    (
        'Wanted: Dead',
        'https://assets-prd.ignimgs.com/2022/06/15/wanteddead-1655334281995.jpg',
        'xbox,playstation,pc',
        '2023-02-04',
        'USA',
        4,
        'Soleil',
        '110 Industries',
        'Wanted: Dead''s shallow combat, dated presentation, and poorly balanced difficulty are the tip of the iceberg of issues that ultimately sinks this disappointing action game from the makers of Ninja Gaiden.',
        'Wanted: Dead is a high-octane, third-person action game featuring spectacular melee combat and exciting gunplay, set in a dark and dangerous version of sci-fi Hong Kong.'),
        (
        'Root [Board Game]',
        'https://assets-prd.ignimgs.com/2023/02/13/root-board-game-button-1676315639013.jpg',
        'pc',
        '2018-08-01',
        'USA',
        9,
        'N/A',
        'Leder Games',
        'Root is a game of adventure and war where 2 to 4 players battle for control of a vast wilderness.',
        'Root works because it is at once familiar and novel: a wargame with a cutesy theme disguising a highly asymmetric strategy affair.'
        ),
        (
        'Hogwarts Legacy',
        'https://assets-prd.ignimgs.com/2022/05/24/hogwarts-legacy-button-fin-1653421326559.jpg',
        'nintendo,pc,xbox,playstation',
        '2023-02-10',
        'UK',
        9.1,
        'Avalanche Software',
        'Warner Bros. Games',
        'In almost every way, Hogwarts Legacy is the Harry Potter RPG I''ve always wanted to play.',
        'Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. Now you can take control of the action and be at the center of your own adventure in the wizarding world!'
        ),
        (
        'Hi-Fi Rush',
        'https://assets-prd.ignimgs.com/2023/01/25/hifirush-1674680068070.jpg',
        'pc,xbox',
        '2023-01-15',
        'USA',
        8.9,
        'Tango Gameworks',
        'Microsoft',
        'Hi-Fi Rush is a rhythm adventure from Tango Gameworks. Playing as wannabe rockstar Chai, you''re the victim of a weird corporate experiment that''s left you able to sense the rhythm of the world to the beat of the game''s soundtrack.',
        'Hi-Fi Rush marches to the beat of its own drum with stunning animation, loveable characters, and stylish rhythmic action that are anything but one-note.'
        ),
        (
        'The Elder Scrolls V: Skyrim -- The Adventure Game',
        'https://assets-prd.ignimgs.com/2021/11/02/skyrim-the-adventure-game-button-1635877139398.jpg',
        'pc',
        '2023-05-02',
        'USA',
        6,
        'Modiphius',
        'The Elder Scrolls',
        'The Elder Scrolls V: Skyrim -- The Adventure Game, based on the blockbuster RPG videogame franchise, is a cooperative or solo adventure board game with hundreds of hours of gameplay. The game changes with each chapter you play and the decisions you make!',
        'The Skyrim board game offers moments of questing joy that eventually dissipate under the shadow of a lackluster main storyline and mediocre components.'
        ),
        (
        'SpongeBob SquarePants: The Cosmic Shake',
        'https://assets-prd.ignimgs.com/2022/08/13/spongebob-squarepants-cosmic-shake-button-fin-1660358126110.jpg',
        'nintendo,pc,xbox,playstation',
        '2023-01-31',
        'USA',
        8,
        'Purple Lamp Studios',
        'THQ Nordic',
        'When the mysterious fortune teller Kassandra grants SpongeBob and Patrick wishes, the two buddies unintentionally open up portals to strange Wishworlds. Explore seven distinct worlds and don more than 30 cosmic skins to rescue the universe in SpongeBob SquarePants: The Cosmic Shake!',
        'SpongeBob SquarePants: The Cosmic Shake is a barebones platformer that manages to be supremely boring despite its SpongeBob-infused charm.'
        ),
        ('Atomic Heart',
    'https://assets-prd.ignimgs.com/2022/11/06/atomic-heart-button-fin-1667702670613.jpg',
    'pc',
    '2023-2-21',
    'Russia',
    8,
    'Mundfish',
    'Focus Entertainment',
    'Atomic Heart is an adventure first-person shooter, events of which unfold in an alternative universe, during the high noon of the Soviet Union.',
    'Atomic Heart is a highly imaginative, atompunk-inspired attempt at picking up where the likes of BioShock left off that makes missteps but definitely has the ticker to punch well above its weight.'),
    (
    'The Legend of Zelda: Breath of the Wild',
    'https://assets-prd.ignimgs.com/2022/06/14/zelda-breath-of-the-wild-1655249167687.jpg',
    'nintendo',
    '2017-3-3',
    'Japan',
    10,
    'Nintendo',
    'Nintendo',
    'Step into a world of discovery, exploration and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series.',
    'The Legend of Zelda: Breath of the Wild is evocative, exhilarating, and a masterclass in open-world design.'),
    (
    'Elden Ring',
    'https://assets-prd.ignimgs.com/2021/06/12/elden-ring-button-03-1623460560664.jpg',
    'pc',
    '2022-2-25',
    'USA',
    10,
    'FromSoftware',
    'Bandai Namco Games',
    'Elden Ring is an expansive fantasy Action-RPG game developed by FromSoftware, Inc. under the direction of Hidetaka Miyazaki and created in collaboration with famed author George R.R. Martin.',
    'Elden Ring is a massive iteration on what FromSoftware began with the Souls series, bringing its relentlessly challenging combat to an incredible open world that gives us the freedom to choose our own path.'),
    (
    'Super Mario Odyssey',
    'https://assets1.ignimgs.com/2017/09/01/super-mario-odyssey-button-fin-1504225715322.jpg',
    'nintendo',
    '2017-10-27',
    'Japan',
    '10',
    '1-Up Studio, Nintendo Entertainment Planning & Development (EPD)',
    'Nintendo',
    'Mario embarks on a new journey through unknown worlds, running and jumping through 3D environments in a sandbox-style game.',
    'Super Mario Odyssey is a brilliant adventure and love letter to the series that made Nintendo a household name.'),
    (
    'Red Dead Redemption 2',
    'https://assets1.ignimgs.com/2016/10/18/red-dead-redemption-2-buttonjpg-f9ad35.jpg',
    'pc',
    '2018-10-26',
    'USA',
    10,
    'Rockstar Studios',
    'Rockstar Games',
    'Red Dead Redemption 2 is an epic tale of life in America''s unforgiving heartland. The game''s vast and atmospheric world also provides the foundation for a brand new online multiplayer experience.',
    'Red Dead Redemption 2 is a game of rare quality; a meticulously polished open-world ode to the outlaw era.'),
    ('Hogwarts Legacy',
    'https://assets-prd.ignimgs.com/2022/05/24/hogwarts-legacy-button-fin-1653421326559.jpg',
    'nintendo',
    '2023-2-10',
    'USA',
    9,
    'Avalanche Software',
    'Warner Bros. Games',
    'Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. Now you can take control of the action and be at the center of your own adventure in the wizarding world!',
    'In almost every way, Hogwarts Legacy is the Harry Potter RPG I''ve always wanted to play.'),
    (
    'Evil West',
    'https://assets-prd.ignimgs.com/2022/11/19/evilwestreview-blogroll-01-1668820004950.jpg',
    'xbox',
    '2022-11-22',
    'USA',
    7,
    'Flying Wild Dog',
    'Focus Home Interactive',
    'Evil West is far from the most complex or innovative action game around, but it nails the most important parts of its old-school, monster-killing campaign.',
    'Evil never sleeps ... but it bleeds. A dark menace consumes the American frontier. As one of the last agents in a top-secret vampire-hunting institute, you are the final line between humanity and a deep-rooted terror that now emerges from the shadows.'),
    (
    'Gungrave G.O.R.E',
    'https://assets-prd.ignimgs.com/2022/11/21/gungravegore-blogroll-02-1669074683468.jpg',
    'playstation',
    '2022-11-22',
    'UK',
    6,
    'Iggymob',
    'Prime Matter',
    'Gungrave G.O.R.E oozes style and has a fantastic combat system, but a lack of variety, aggravating difficulty spikes, and often-frustrating design decisions keep it from reaching its full potential.',
    'Gungrave G.O.R.E. marks the return of the Gunslinger of Resurrection. Play as Grave, the gun-wielding badass anti-hero, and you mow down tons of enemies in a gory ballet of bullets through a story of vengeance, love and loyalty, all in third-person hack-and-slash/shooter combat.'),
    ('Warhammer 40,000: Darktide',
    'https://assets-prd.ignimgs.com/2022/11/23/warhammer40000darktide-blogroll-1669247343837.jpg',
    'pc',
    '2022-11-30',
    'USA',
    8,
    'Fatshark',
    'Fatshark',
    'Performance issues aside, Warhammer 40,000: Darktide''s ferocious battles make for some of the most thrilling co-op action in years.',
    'Go deep into the hive city of the 41st Millennium and face hordes of enemies you have only seen in your nightmares in the 4-player co-op action game Warhammer 40,000: Darktide.'),
    ('Pokemon Scarlet',
    'https://assets-prd.ignimgs.com/2022/11/23/pokemonscarletviolet-review2-blogroll-1669162921155.jpg',
    'nintendo',
    '2022-11-18',
    'Japan',
    6,
    'Game Freak',
    'Nintendo',
    'The open-world gameplay of Pokémon Scarlet and Violet is a brilliant direction for the future of the franchise, but this promising shift is sabotaged by the numerous ways in which Scarlet and Violet feel deeply unfinished.',
    'Catch never-before-seen Pokemon and explore a brand new region created playable with new open-world gameplay in Pokemon Scarlet and Pokemon Violet! Brand new Pokemon populate this world -- who will be your new starter partner: Sprigatito, Fuecoco, or Quaxly?'),
    ('Midnight Suns',
    'https://assets-prd.ignimgs.com/2022/11/30/midnightsun-blogroll-1669773428429.jpg',
    'playstation',
    '2022-10-2',
    'USA',
    8,
    'Firaxis',
    '2K Games',
    'Marvel''s Midnight Suns is an expansive tactical RPG that makes great use of card game mechanics to inject variety and unpredictability into its excellent combat.',
    'Set in the darker side of the Marvel Universe, Marvel''s Midnight Suns is a tactical RPG that sees you fighting alongside and forging friendships with iconic Marvel heroes spanning The Avengers, X-Men, Runaways, and more.'),
    ('The Callisto Protocol',
    'https://assets-prd.ignimgs.com/2022/12/01/callistoprotocol-blogroll-1669873578077.jpg',
    'pc',
    '2022-10-2',
    'USA',
    7,
    'Striking Distance Studios',
    'Krafton',
    'The Callisto Protocol is a satisfyingly gory spiritual successor to the Dead Space series, but it''s ultimately more of a striking modern mimic than a scary new mutation.',
    'From Striking Distance Studios and the creators of Dead Space, comes The Callisto Protocol – a terrifying, story-driven, survival horror game set in a prison colony on Jupiter''s dead moon Callisto.'),
    (
    'The Dark Pictures: The Devil In Me', 
    'https://assets-prd.ignimgs.com/2022/11/06/the-dark-pictures-the-devil-in-me-button-fin-1667703164604.jpg', 
    'xbox,playstation,pc', 
    '2022-11-18', 
    'UK', 
    5, 
    'Supermassive Games', 
    'Bandai Namco Games', 
    'The Dark Pictures Anthology: The Devil in Me, also known simply as The Devil in Me, is a 2022 interactive drama and survival horror with slasher horror elements game developed by Supermassive Games and published by Bandai Namco Entertainment', 
    'The Devil in Me features a cast of five playable protagonists and a multilinear gameplay narrative influenced by player choice. The game''s decision-making scenes, of which there are several, can significantly alter the trajectory of the plot and change the relationships between the main characters. The title introduced new features, such as character inventory, tool-based puzzles, and new movement capabilities such as running, jumping, and climbing.'
	),
    (
    'Atari 50: The Anniversary Celebration', 
    'https://assets-prd.ignimgs.com/2022/11/01/atari-50-button-02-1667327720413.jpg', 
    'xbox,playstation,pc,nintendo',
    '2022-11-12', 
    'USA',
    9, 
    'Digital Eclipse Software',
    'Atari', 
    'Atari 50: The Anniversary Celebration, or simply Atari 50, is a video game compilation and interactive documentary about the history of Atari that comprises newly shot interviews with former Atari employees, archival footage, emulated games', 
    'The main feature of the game is an interactive timeline that lays out the history of the company and its products in an intuitive way.'
	),
    (
    'Goat Simulator 3', 
    'https://assets-prd.ignimgs.com/2022/06/12/goatsimulator3-button-1654997237296.jpg', 
    'xbox,playstation,pc', 
    '2022-11-17',
    'Sweden', 
    8, 
    'Coffee Stain', 
    'Coffee Stain', 
    'Goat Simulator 3 is an action video game and the sequel to Goat Simulator. The game was announced during Summer Game Fest and was released on November 17, 2022.',
    'The game features a four-player cooperative mode, and it is set on the fictional island of San Angora. It is an action game played in a third-person perspective where the goal, controlling the goat player character, is to wreak havoc and perform stunts in the urban environment of game.'
    ),
    (
    'Somerville', 
    'https://assets1.ignimgs.com/2017/06/27/somerville-button-1-1498585639616.jpg', 
    'xbox,pc', 
    '2022-11-14', 
    'UK', 
    7,
    'Jumpship', 
    'Jumpship', 
    'Somerville is an adventure video game and the debut title by the independent studio Jumpship.',
    'Somerville is an adventure game played from a third-person perspective with platform game-like elements and physics-based puzzles. The game is presented without dialogue or narration, instead using the setting, environments, and animations to tell the story. The player controls the father of an everyday family as an alien invasion begins, and must guide the family across various environments, some of which are patrolled by alien creatures and machines.'
    ),
    ('Pentiment', 
    'https://assets-prd.ignimgs.com/2022/06/12/pentiment-button-fin-1655069953648.jpg',
    'xbox,pc', 
    '2022-11-15', 
    'USA',
    10, 
    'Obsidian Entertainment',
    'Xbox Game Studios',
    'Pentiment is an adventure video game by Obsidian Entertainment and published by Xbox Game Studios.', 
    'Pentiment is a narrative adventure 2D role-playing video game set in Duchy of Bavaria, in a fictional Alpine town of Tassing and its nearby abbey, in early to middle 16th century. The player is tasked with investigating a series of murders of prominent individuals for which other townsfolk have been accused for various reasons. The game''s art style is a mix of late medieval manuscripts, early print, and woodcuts at the transition from late medieval to early modern art.'
    ),
    (
    'Vampire Survivors', 
    'https://assets-prd.ignimgs.com/2022/11/12/vampire-survivors-button-fin-1668290394529.jpg', 
    'xbox,pc',
    '2021-12-17',
    'UK',
    7, 
    'Poncle', 
    'Poncle',
    'Vampire Survivors is a roguelike shoot ''em up video game developed and published by Luca Galante, also known as poncle.', 
    'The player controls an automatically attacking character while fighting against continuous waves of monsters, with the goal being to survive the onslaught for as long as possible and unlock additional characters, weapons, and relics for subsequent sessions. In spite of the name and key art, none of the variety of monsters encountered are vampires in the game.'    ),
    
    (
    'Among Us VR',
    'https://assets-prd.ignimgs.com/2022/01/28/among-us-vr-button-1643350703959.jpg',
    'pc, playstation',
    '2022-11-10',
    'USA',
     8,
    'Innersloth, Robot Teddy',
    'Schell Games',
    'Among Us VR is a party game of teamwork and betrayal. Crewmates work together in this virtual world to complete tasks before one or more Impostors can kill everyone aboard.',
    'Among Us VR is a strong remake of Innersloth social deduction hit. While Schell Games take could do with extra content, it makes up for this with polished gameplay.'
    ),
    (
    'Sonic Frontiers', 
    'https://assets-prd.ignimgs.com/2022/10/12/sonic-frontiers-button-fin-1665602954137.jpg',
    'xbox, playstation, nintendo, pc',
    '2022-11-08',
    'Japan',
     7,
    'Sonic Team',
    'Sega',
    'Sonic Frontiers is a 2022 platform game developed by Sonic Team and published by Sega. As Sonic, the player explores the Starfall Islands to collect the Chaos Emeralds, after Sonic and his friends are separated when falling through a wormhole.',
    'Sonic Frontiers is the iconic franchise the first ever open-zone-inspired gaming experience, bringing Sonic fans an all-new type of Sonic rush. In the dangerous and vast world of Sonic Frontiers, anything is possible, and players will have the freedom to explore the visually stunning, open-zone realm.'
    ),
    (
    'Marvel Snap',
    'https://assets-prd.ignimgs.com/2022/05/20/marvel-snap-button-1-1653021420358.jpg',
     'pc',
    '2022-10-18', 
    'USA',
    8,
    'Second Dinner Studios',
    'Nuverse',
    'Marvel Snap is a digital collectible card game developed by Second Dinner and published by Nuverse for Microsoft Windows, Android and iOS. The game features a collection of different Marvel characters from the Marvel Universe. The game was released on October 18, 2022, after a period of beta testing.',
    'Marvel Snap packs bold ideas, deep gameplay, a punchy presentation and lots of love for Marvel. Its approach to building a collection and randomness in gameplay would not be for everyone, but it is still well worth playing.'),
    (
    'The Entropy Centre',
    'https://assets-prd.ignimgs.com/2022/06/12/entropycentre-1655000747488.jpg',
    'playstation',
    '2022-11-3',
    'USA',
    7,
    'Stubby Games',
    'Playstack',
    'The Entropy Centre is a mind-bending puzzle adventure where you reverse objects through time to overcome seemingly impossible obstacles and conundrums. Manipulate time to your will and solve ingeniously challenging puzzle rooms, each one taking you closer to the heart of a colossal space station in orbit of Earth.',
    'The Entropy Centre is a first-person shooter built around a unique puzzle mechanic that allows players to think in reverse and overcome seemingly impossible obstacles.'
    ),
    (
    'Resident Evil VIllage',
    'https://assets-prd.ignimgs.com/2021/01/22/re-village-button-fin-1611277715193.jpg?',
    'playstation ',
    '2021-5-7',
    'USA',
    5,
    'Capcom',
    'Ubitus K.K',
    'Fear surrounds you in Resident Evil Village, the eighth main entry in the storied Resident Evil horror franchise.',
    'Resident Evil Village is a 2021 survival horror game developed and published by Capcom. It is the sequel to Resident Evil 7: Biohazard. Players control Ethan Winters, who searches for his kidnapped daughter in a village filled with mutant creatures'
    ),
    (
    'God of War: Ragnarok',
    'https://assets-prd.ignimgs.com/2021/09/09/god-of-war-ragnarok-button-1631231879154.jpg',
    'playstation',
    '2022-11-9',
    'USA',
    10,
    'Santa Monica Studio',
    'Sony Interactive Entertainment',
    'God of War Ragnarök is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. It was released worldwide on November 9, 2022, for the playstation 4 and playstation 5, marking the first cross-gen release in the God of War series',
    'Join Kratos and Atreus on a mythic journey for answers before Ragnarök arrives. Together, father and son must put everything on the line as they journey to each of the Nine Realms in God of War Ragnarök, the brutal and epic sequel in the action franchise.'
    );